default_install_hook_types: [pre-commit]
default_stages: [pre-commit] #  Use 'commit' to apply to commit stage; 'pre-commit' is redundant here

# Minimum required version of pre-commit
minimum_pre_commit_version: "2.18"

repos:
  - repo: https://github.com/sqlfluff/sqlfluff
    rev: 3.3.0
    hooks:
      - id: sqlfluff-lint
        additional_dependencies:
          - dbt-postgres==1.9.0
          - sqlfluff-templater-dbt==3.3.0
      - id: sqlfluff-fix
        stages: [manual] #  This command is available only to run manually
        additional_dependencies:
          - dbt-postgres==1.9.0
          - sqlfluff-templater-dbt==3.3.0

  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.35.1
    hooks:
      - id: yamllint
        args: [-c=.yamllint]

  - repo: https://github.com/dbt-checkpoint/dbt-checkpoint
    rev: v2.0.6
    hooks:
      - id: dbt-docs-generate
      - id: check-source-table-has-description
      - id: check-model-columns-have-desc
      - id: check-model-has-all-columns
      - id: check-model-has-tests
        args:
          - --test-cnt
          - "2"
          - --

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v4.0.0-alpha.8" #  Check for the latest version on the repository
    hooks:
      - id: prettier
        args: ["--write"]
        types: [yaml]
