
model-paths: 
- models
analysis-paths: 
- analyses
test-paths: 
- tests
seed-paths: 
- seeds
macro-paths: 
- macros
snapshot-paths: 
- snapshots

clean-targets:     
- target
- dbt_packages

models:
  jaffle:
    aggregates:
      +schema: dbt_jaffle_agg
      +materialized: table
      +docs:
        node_color: '#FFD700'

    core:
      +schema: dbt_jaffle_core
      +materialized: table
      +docs:
        node_color: '#006400'

    intermediate:
      +schema: dbt_jaffle_imd
      +materialized: table
      +docs:
        node_color: '#4f42b5'

    staging:
      +schema: dbt_jaffle_stg
      +materialized: view
      +docs:
        node_color: '#FFA500'

name: 'jaffle'
profile: 'jaffle'
seed-paths:
- seeds
seeds:
    +schema: dbt_jaffle_stg
    +docs:
      node_color: '#FFA500'
snapshot-paths:
- snapshots
snapshots:
    +docs:
      node_color: '#FFA500'
target-path: target
test-paths:
- tests
vars:
  null_default_string: "'null'"
version: 1.0.0